[project]
name = "arxivius"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pymupdf>=1.26.1",
    "scrapy>=2.13.2",
]
